CC     = gcc
CFLAGS = -Wall -g -O0 -m32
ARCH = Linux.x86
LDIR=contrib/${ARCH}
 
all: 7800heat.${ARCH}
 
7800heat.${ARCH}: 7800heat.c
	$(CC) $(CFLAGS) 7800heat.c -o $@ -L${LDIR}/lib -I${LDIR}/include -lm
 
clean:
	rm -f 7800heat.${ARCH}

